import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getSession } from "@/lib/authActions";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGlobe, faHouse } from "@fortawesome/free-solid-svg-icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// the navigation bar
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const tokenContent = await getSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center justify-between flex-wrap bg-bg-shade p-6">
          <Link href="/">
            <Image
              src="/TaskQuest.png"
              alt="something"
              width={50}
              height={50}
            ></Image>
            <div className="flex items-center flex-shrink-0 text-foreground mr-6">
              <span className="font-semibold text-xl tracking-tight">
                TaskQuest
              </span>
            </div>
          </Link>
          <div className="lg:flex lg:items-center lg:w-auto justify-end">
            <ul className="flex">
              {tokenContent ? (
                <>
                  <li className="mr-4">
                    <Link
                      href="/"
                      className="block mt-4 font-bold lg:inline-block lg:mt-0 text-foreground hover:text-foreground-opose"
                    >
                      <p>
                        Home <FontAwesomeIcon icon={faHouse} size="1x" />
                      </p>
                    </Link>
                  </li>

                  <li className="mr-4">
                    <Link
                      href="/shared"
                      className="block mt-4 font-bold lg:inline-block lg:mt-0 text-foreground hover:text-foreground-opose"
                    >
                      <p>
                        Public <FontAwesomeIcon icon={faGlobe} size="1x" />
                      </p>
                    </Link>
                  </li>
                </>
              ) : (
                <></>
              )}
            </ul>
          </div>
        </nav>
        <div className="pt-4 bg-inherit w-full">{children}</div>
      </body>
    </html>
  );
}
